-- MySQL Script generated by MySQL Workbench
-- Tue Oct  8 18:31:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema activity1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema activity1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `activity1` DEFAULT CHARACTER SET utf8 ;
USE `activity1` ;

-- -----------------------------------------------------
-- Table `activity1`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `activity1`.`posts` (
  `PostID` INT NOT NULL AUTO_INCREMENT,
  `user.ID Post By` INT NULL,
  `user.ID Last Post` INT NULL,
  `Title` VARCHAR(30) NOT NULL,
  `Content` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`PostID`),
  INDEX `ID_idx` (`user.ID Post By` ASC, `user.ID Last Post` ASC),
  INDEX `user.ID_idx` (`user.ID Last Post` ASC),
  CONSTRAINT `ID`
    FOREIGN KEY (`user.ID Post By` , `user.ID Last Post`)
    REFERENCES `activity1`.`users` (`ID` , `ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user.ID`
    FOREIGN KEY (`user.ID Last Post`)
    REFERENCES `activity1`.`users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
